/**
 * Auto-generated by scripts/stamp-build.mjs (npm run stamp / build:pages).
 * Do not edit by hand -- re-run stamp to bump.
 */
export const BUILD_INFO = {
  version: "0.1.3",
  stampedAt: "2026-08-12T15:40:45.887Z",
  label: "v0.1.3 | 2026-08-12 11:40",
};

export default BUILD_INFO;
