/**
 * Auto-generated by scripts/stamp-build.mjs (npm run stamp / build:pages).
 * Do not edit by hand -- re-run stamp to bump.
 */
export const BUILD_INFO = {
  version: "0.1.7",
  stampedAt: "2026-08-22T02:16:02.765Z",
  label: "v0.1.7 | 2026-08-21 22:16",
};

export default BUILD_INFO;
