/**
 * Bump package.json patch and write src/config/buildInfo.js for HUD / Pages verify.
 * Run via: npm run stamp (also chained by build:pages).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const pkgPath = join(root, 'package.json');
const outPath = join(root, 'src', 'config', 'buildInfo.js');

const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
const parts = String(pkg.version || '0.1.0').split('.').map((n) => parseInt(n, 10) || 0);
while (parts.length < 3) parts.push(0);
parts[2] += 1;
const version = `${parts[0]}.${parts[1]}.${parts[2]}`;

const now = new Date();
const stampedAt = now.toISOString();
const pad = (n) => String(n).padStart(2, '0');
const localStamp = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${pad(now.getHours())}:${pad(now.getMinutes())}`;
const label = `v${version} | ${localStamp}`;

pkg.version = version;
writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`, 'utf8');

const fileBody = `/**
 * Auto-generated by scripts/stamp-build.mjs (npm run stamp / build:pages).
 * Do not edit by hand -- re-run stamp to bump.
 */
export const BUILD_INFO = {
  version: ${JSON.stringify(version)},
  stampedAt: ${JSON.stringify(stampedAt)},
  label: ${JSON.stringify(label)},
};

export default BUILD_INFO;
`;

writeFileSync(outPath, fileBody, 'utf8');
console.log(`[stamp-build] ${label}`);
